sudo: false
cache: pip
language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6
    - python: 3.5
    - python: 2.7

install:
  - pip install -r requirements-dev.txt
  - pip install tox-travis
  - pip install -e .

script:
  - tox
